# Constants for segmentation parameters and settings

DISPLAY_WINDOW = 800
DISPLAY_LEVEL = 200


MIN_MYOCARDIUM_THRESHOLD_VALUE = -120
MAX_MYOCARDIUM_THRESHOLD_VALUE = 300
MIN_SCAR_THRESHOLD_VALUE = -90
MAX_SCAR_THRESHOLD_VALUE = -60

SEGMENTATION_QUALITY = "normal"
SEGMENTATION_TASK = "heartchambers_highres"

LOGICAL_UNION = "UNION"
LOGICAL_INTERSECT = "INTERSECT"
LOGICAL_SUBTRACT = "SUBTRACT"
