# Constants for cardiac segmentation editor effects

MIN_THRESHOLD_VALUE = -1024
MAX_THRESHOLD_VALUE = 3071
MIN_MYOCARDIUM_THRESHOLD_VALUE = -90 
MIN_MYOCARDIUM_THRESHOLD_VALUE = -90 
MAX_MYOCARDIUM_THRESHOLD_VALUE = 300
MIN_SCAR_THRESHOLD_VALUE = -1024
MAX_SCAR_THRESHOLD_VALUE = -50

INNER_MYOCARDIUM_LIMIT = 33
MIDDLE_MYOCARDIUM_LIMIT = 67

RIGHT_MYOCARDIUM_GROWTH = 1.0
LEFT_MYOCARDIUM_GROWTH = 1.0

PLEURAL_BORDER_WIDTH = 4.0

EDITABLE_ANYWHERE = 0
EDITABLE_OUTSIDE_ALL_SEGMENTS = 3

WALL_THICKNESS_THRESHOLD_MM = 11.0
WALL_THICKNESS_STEP_MM = 0.5
